name: Test Executables

on:
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            os_name: linux
          - os: macos-latest
            os_name: mac
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            console.log("Workflow Run ID:", context.payload.workflow_run.id);
            console.log("Workflow Run Number:", context.payload.workflow_run.run_number);
            console.log("Workflow Name:", context.payload.workflow_run.name);
            
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            
            console.log("All artifacts:", artifacts.data.artifacts.map(a => a.name));
            
            const matchArtifact = artifacts.data.artifacts.find((artifact) => {
              return artifact.name == "jo_${{ matrix.os_name }}"
            });
            
            if (!matchArtifact) {
              core.setFailed(`No artifact found with name jo_${{ matrix.os_name }}`);
              return;
            }
            
            console.log("Matching artifact:", matchArtifact);
            
            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            
            fs.writeFileSync('artifact.zip', Buffer.from(download.data));
            console.log("Artifact downloaded and saved as artifact.zip");

      - name: Unzip artifact
        run: unzip artifact.zip

      - name: Run ls
        run: ls -la
        
      - name: Make binary executable
        run: chmod +x jo_${{ matrix.os_name }}

      - name: Run binary
        run: timeout 20s ./jo_${{ matrix.os_name }}

      - name: Check exit status
        run: |
          if [ $? -eq 124 ]; then
            echo "Program terminated successfully after timeout"
            exit 0
          else
            echo "Program terminated unexpectedly"
            exit 1
          fi
